spring:
  application:
    name: Tests
  datasource:
    url: jdbc:h2:mem:lel
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:      enabled: true
      path: /db
  jpa:
    show-sql: true
      
